# Generated by Django 5.1.6 on 2025-03-04 01:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='human')),
                ('available', models.BooleanField(default=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shoe_size', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waist_size', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bust_size', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hip_size', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=250)),
                ('hair_color', models.CharField(blank=True, max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sobaka.category')),
            ],
            options={
                'verbose_name': 'human',
                'verbose_name_plural': 'humans',
                'ordering': ('name',),
            },
        ),
    ]
