# Generated by Django 5.1.7 on 2025-03-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobaka', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='human',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='human',
            name='image2',
            field=models.ImageField(blank=True, upload_to='human'),
        ),
        migrations.AddField(
            model_name='human',
            name='image3',
            field=models.ImageField(blank=True, upload_to='human'),
        ),
        migrations.AddField(
            model_name='human',
            name='image4',
            field=models.ImageField(blank=True, upload_to='human'),
        ),
        migrations.AddField(
            model_name='human',
            name='image5',
            field=models.ImageField(blank=True, upload_to='human'),
        ),
    ]
