# Generated by Django 5.1.7 on 2025-03-16 14:31

import sobaka.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobaka', '0002_rename_image_human_image1_human_image2_human_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='description',
        ),
        migrations.AlterField(
            model_name='human',
            name='image1',
            field=models.ImageField(blank=True, upload_to=sobaka.models.upload_to_human),
        ),
        migrations.AlterField(
            model_name='human',
            name='image2',
            field=models.ImageField(blank=True, upload_to=sobaka.models.upload_to_human),
        ),
        migrations.AlterField(
            model_name='human',
            name='image3',
            field=models.ImageField(blank=True, upload_to=sobaka.models.upload_to_human),
        ),
        migrations.AlterField(
            model_name='human',
            name='image4',
            field=models.ImageField(blank=True, upload_to=sobaka.models.upload_to_human),
        ),
        migrations.AlterField(
            model_name='human',
            name='image5',
            field=models.ImageField(blank=True, upload_to=sobaka.models.upload_to_human),
        ),
    ]
