# Generated by Django 5.1.7 on 2025-03-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobaka', '0003_remove_human_description_alter_human_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='bust_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='human',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='human',
            name='hip_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='human',
            name='shoe_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='human',
            name='waist_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
