# Generated by Django 5.1.7 on 2025-04-13 15:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobaka', '0006_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='news')),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'news article',
                'verbose_name_plural': 'news articles',
                'ordering': ['-created'],
            },
        ),
    ]
