# Generated by Django 5.2 on 2025-04-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_duration_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
