# Generated by Django 5.1.7 on 2025-04-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
