# Generated by Django 5.1.6 on 2025-03-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
