# Generated by Django 5.1.7 on 2025-04-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_options_alter_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
